# Generated by Django 4.1.7 on 2023-02-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("catalog", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("catalog", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="credential",
            name="id",
        ),
        migrations.AddField(
            model_name="credential",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Sync",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("schedule", models.JSONField()),
                ("destination", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.destination")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.source")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace")),
            ],
        ),
        migrations.AddField(
            model_name="source",
            name="credential",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.credential"),
        ),
        migrations.AddField(
            model_name="source",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace")),
            ],
        ),
        migrations.AddField(
            model_name="destination",
            name="credential",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.credential"),
        ),
        migrations.AddField(
            model_name="destination",
            name="workspace",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.workspace"),
        ),
        migrations.AddField(
            model_name="credential",
            name="workspace",
            field=models.ForeignKey(
                default="042a7c78-d07e-4ab0-8b67-34e8429949ac",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.workspace",
            ),
            preserve_default=False,
        ),
    ]
