# Generated by Django 3.1.5 on 2023-03-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230308_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connector',
            old_name='image_name',
            new_name='docker_image',
        ),
        migrations.RenameField(
            model_name='connector',
            old_name='image_tag',
            new_name='docker_tag',
        ),
    ]
