# Generated by Django 4.1.7 on 2023-02-27 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_destination_source_workspace_remove_credential_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="credential",
            old_name="uuid",
            new_name="id",
        ),
    ]
