# Generated by Django 3.1.5 on 2023-02-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230227_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='workspace',
            new_name='workspaces',
        ),
    ]
