# Generated by Django 3.1.5 on 2023-03-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230308_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='display_name',
            field=models.CharField(default='DUMMY_CONNECTOR_DISPLAY_NAME', max_length=128),
        ),
    ]
