# Generated by Django 3.1.5 on 2023-02-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230227_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='workspaces',
            new_name='workspace',
        ),
    ]
