# Generated by Django 3.1.5 on 2023-02-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230227_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='workspace',
        ),
        migrations.AddField(
            model_name='workspace',
            name='organization',
            field=models.ForeignKey(default='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
            preserve_default=False,
        ),
    ]
