# Generated by Django 3.1.5 on 2023-05-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230309_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='sync',
            name='ui_state',
            field=models.JSONField(null=True),
        ),
    ]
