# Generated by Django 3.1.5 on 2023-06-05 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sync_ui_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('external_id', models.CharField(max_length=256)),
                ('profile', models.CharField(max_length=256, null=True)),
                ('meta_data', models.JSONField(null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.account'),
        ),
    ]
