# Generated by Django 3.1.5 on 2023-03-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230301_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='core.credential'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='source',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.credential'),
        ),
        migrations.AlterField(
            model_name='source',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='sync',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='core.destination'),
        ),
        migrations.AlterField(
            model_name='sync',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='core.source'),
        ),
        migrations.AlterField(
            model_name='sync',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='core.workspace'),
        ),
    ]
