# Generated by Django 3.1.5 on 2023-03-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230301_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='DUMMY_CONNECTOR', max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='credential',
            name='connector_type',
        ),
        migrations.AddField(
            model_name='credential',
            name='connector',
            field=models.ForeignKey(default='DUMMY_CONNECTOR', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='core.connector'),
            preserve_default=False,
        ),
    ]
