# Generated by Django 3.1.5 on 2023-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230605_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.TextField(null=True),
        ),
    ]
