# Generated by Django 3.1.5 on 2023-03-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230301_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='connector_id',
            new_name='connector_type',
        ),
    ]
