# Generated by Django 3.1.5 on 2024-02-12 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_connector_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='oauth_keys',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')],
                                   default='private', max_length=64),
        ),
        migrations.CreateModel(
            name='OAuthApiKeys',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
                 editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, default='DUMMY_CONNECTOR', max_length=64, null=True)),
                ('oauth_config', models.JSONField(null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='oauth_api_keys', to='core.workspace')),
            ],
            options={
                'db_table': 'core_oauth_api_keys',
            },
        ),
        migrations.AddConstraint(
            model_name='oauthapikeys',
            constraint=models.UniqueConstraint(fields=('workspace', 'type'), name='unique_oauth_keys'),
        ),
    ]
