# Generated by Django 3.1.5 on 2023-03-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230301_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='workspace_id',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='credential_id',
            new_name='credential',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='workspace_id',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='credential_id',
            new_name='credential',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='workspace_id',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='sync',
            old_name='destination_id',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='sync',
            old_name='workspace_id',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='workspace',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
