# Generated by Django 3.1.5 on 2024-01-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_connector_oauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApiKeys',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='DUMMY_CONNECTOR', max_length=64, primary_key=True, serialize=False)),
                ('oauth_config', models.JSONField(null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_api_keys', to='core.workspace')),
            ],
            options={
                'db_table': 'oauth_api_keys',
            },
        ),
    ]
