# Generated by Django 3.1.5 on 2024-01-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_oauthapikeys'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthapikeys',
            table='core_oauth_api_keys',
        ),
    ]
