# Generated by Django 3.1.5 on 2024-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240212_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='mode',
            field=models.CharField(default='DUMMY_CONNECTOR_MODE', max_length=64),
        ),
    ]
