# Generated by Django 3.1.5 on 2024-04-02 08:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240212_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageCredentials',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'), editable=False, primary_key=True, serialize=False)),
                ('connector_config', models.JSONField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_credentials', to='core.workspace')),
            ],
        ),
    ]
