# Generated by Django 3.1.5 on 2023-03-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230301_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='connector_type',
            new_name='connector',
        ),
    ]
