# Generated by Django 3.1.5 on 2024-04-02 12:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240212_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='mode',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
    ]
