# Generated by Django 3.1.5 on 2024-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240123_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='oauth_keys',
            field=models.CharField(choices=[('public', 'PUBLIC'), ('private', 'PRIVATE')], default='private', max_length=64),
        ),
    ]
