# Generated by Django 3.1.5 on 2023-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230301_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.CharField(default='DUMMY_NAME', max_length=256),
            preserve_default=False,
        ),
    ]
