# Generated by Django 3.1.5 on 2024-04-02 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_connector_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connector',
            name='mode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='DUMMY_CONNECTOR_MODE', max_length=64), size=None),
        ),
    ]
