# Generated by Django 3.1.5 on 2024-04-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='DUMMY_CONNECTOR_DISPLAY_NAME', max_length=128)),
                ('query', models.CharField(default='SELECT * FROM products', max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
    ]
