# Generated by Django 3.1.5 on 2024-04-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20240412_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='updated_at',
        ),
    ]
