# Generated by Django 3.1.5 on 2024-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240412_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='package',
        ),
        migrations.AddField(
            model_name='prompt',
            name='package_id',
            field=models.CharField(default='P0', max_length=20),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
