# Generated by Django 3.1.5 on 2024-04-15 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20240412_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='gated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Explore',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'), editable=False, primary_key=True, serialize=False)),
                ('ready', models.BooleanField(default=False)),
                ('spreadsheet_url', models.URLField(blank=True, default='https://example.com', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_account', to='core.account')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_prompt', to='core.prompt')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_workspace', to='core.workspace')),
            ],
        ),
    ]
