# Generated by Django 3.1.5 on 2024-04-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20240415_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=256, primary_key=True,serialize=False),
        ),
    ]
