# Generated by Django 3.1.5 on 2024-04-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240415_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='package',
            name='gated',
            field=models.BooleanField(default=True),
        ),
    ]
