# Generated by Django 3.1.5 on 2024-04-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20240416_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='name',
            field=models.CharField(default='aaaaaa', max_length=256),
        ),
        migrations.AddField(
            model_name='prompt',
            name='description',
            field=models.CharField(default='aaaaaa', max_length=1000),
        ),
    ]
