# Generated by Django 3.1.5 on 2024-05-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_explore_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='sync',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_sync', to='core.sync'),
        ),
    ]
