# Generated by Django 3.1.5 on 2024-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20240503_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='query',
        ),
        migrations.AddField(
            model_name='prompt',
            name='type',
            field=models.CharField(default='SRC_SHOPIFY', max_length=256),
        ),
    ]
