# Generated by Django 3.1.5 on 2024-05-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20240503_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='parameters',
            new_name='spec',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='query',
        ),
        migrations.AddField(
            model_name='prompt',
            name='type',
            field=models.CharField(default='SRC_SHOPIFY', max_length=256),
        ),
    ]
