# Generated by Django 3.1.5 on 2024-05-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20240503_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta',
            field=models.JSONField(default=dict),
        ),
    ]
