# Generated by Django 3.1.5 on 2024-05-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20240507_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='parameters',
            new_name='spec',
        ),
    ]
