# Generated by Django 3.1.5 on 2024-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_prompt_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='prompt',
            name='operators',
            field=models.JSONField(default={'integer': ['=', '>', '<', '>=', '<=', '!='], 'string': ['=', '!=', 'IN', 'NOT IN']}),
        ),
    ]
