# Generated by Django 3.1.5 on 2024-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20240607_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='time_grain_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
