# Generated by Django 3.1.5 on 2024-06-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_prompt_time_grain_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='time_window_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
