# Generated by Django 3.1.5 on 2024-07-16 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_prompt_time_window_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ifttt',
            fields=[
                ('store_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=32768)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifttts', to='core.workspace')),
            ],
        ),
    ]
