# Generated by Django 3.1.5 on 2024-07-16 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_prompt_time_window_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTokens',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
                 editable=False, primary_key=True, serialize=False)),
                ('write_key', models.CharField(max_length=256)),
                ('link_id', models.CharField(max_length=256)),
                ('store_id', models.CharField(max_length=256)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='channel_tokens', to='core.workspace')),
            ],
        ),
    ]
