# Generated by Django 3.1.5 on 2024-07-17 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_prompt_time_window_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storefront',
            fields=[
                ('platform', models.CharField(max_length=256)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceStorefront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storefront')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Ifttt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=32768)),
                ('storefront', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.storefront')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelTopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_key', models.CharField(max_length=256)),
                ('channel', models.CharField(default='chatbox', max_length=32)),
                ('link_id', models.CharField(max_length=256)),
                ('storefront', models.ForeignKey(default='dummy-store-front', on_delete=django.db.models.deletion.CASCADE, to='core.storefront')),
            ],
        ),
    ]
