# Generated by Django 3.1.5 on 2024-07-17 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_ifttt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTopics',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
                 editable=False, primary_key=True, serialize=False)),
                ('write_key', models.CharField(max_length=1024)),
                ('channel_type', models.CharField(default='chatbox', max_length=32)),
                ('link_id', models.CharField(max_length=1024)),
                ('store_id', models.CharField(max_length=1024)),
            ],
        ),
    ]
