# Generated by Django 3.1.5 on 2024-07-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_channeltopics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeltopics',
            old_name='channel_type',
            new_name='channel',
        ),
    ]
