# Generated by Django 3.1.5 on 2024-07-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_channeltopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='channeltopics',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='channeltopics', to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='channeltopics',
            name='channel_type',
            field=models.CharField(default='chatbox', max_length=9999),
        ),
        migrations.AlterField(
            model_name='channeltopics',
            name='link_id',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='channeltopics',
            name='store_id',
            field=models.CharField(max_length=9999),
        ),
        migrations.AlterField(
            model_name='channeltopics',
            name='write_key',
            field=models.CharField(max_length=9999),
        ),
    ]
