# Generated by Django 3.1.5 on 2024-07-18 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20240718_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='valmiuseridjitsuapitoken',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jitsuapitoken', to='core.workspace'),
        ),
    ]
